### ISSUE TITLE
memory leak when exiting with an error

### ISSUE THREAD

**Issue by pts** [pts/sam2p#12]
Example: many memory leaks reported with `valgrind --leak-check=full --show-reachable=yes ./sam2p.yes -j -s:Gray1:stop examples/ptsbanner.bmp t.png`. No memory leaks without the `-s:Gray1:stop`, because that's a successful invocation.

This will be a lot of work to fix, because error exits are everywhere in the codebase.

**Comment by fgeek** [comment]
@pts It's normal that valgrind reports memory leaks when program exits abnormally.

**Comment by pts** [comment]
Correct, right now error exits have lots of memory leaks. It would be too much work to fix it.
