### ISSUE TITLE
hq.pl will be broken come Perl 5.26

### ISSUE THREAD

**Issue by kentfredric** [pts/sam2p#2]
Perl 5.26 is removing `.` ( CWD ) from the list of default directories in its `@INC` load path.

As a result, `do "hq.pl"` ( which hq.pl for some reason calls ) now fails as there is no longer any "hq.pl" in the `@INC`  path.

Even though the documentation for `do` seems to suggest 

```perl
do "File"
```

functions the same as

```perl
eval `cat File`
```

this was not true, and the reason it gave that impression was due to the assumption that `.` would be in `@INC`, and so was more like:

```perl
sub resolve {
     my $file = shift;
     # special case for absolute paths
     if ( is_abspath( $file ) ) {
        return $file;
     }
    # special case for paths with explicit "." prefix.
    if ( $file =~ qr{^[.]{1,2}/} ) {
       return $file;
    }
    for my $prefix ( @INC ) {
       next unless -e "${prefix}/${file}"   
       return "${prefix}/${file}"
    }
    die "Can't find $file in \@INC";
}
my $realpath = resolve("File");
eval `cat $realpath`
```
Which of course worked the same for  `require "File"` as `require "./File"`  when `@INC` contained `.`
But as `@INC` no longer contains `.` , only the special-cased branch for `./` works.

Subsequently, compiling sam2p under Perl 5.26 now breaks as follows:

```
<l1lzw.psm >l1gbl.pst.tmp.h perl -pe0
x86_64-pc-linux-gnu-g++ -E -DCFG_FMT_ZLIB_ONLY=1 -DNDEBUG=1 -DCFG_NO_VAR_S=1 -DUSE_NO_BIND=1 -DUSE_SHORT_NAMES=1 -DUSE_CURRENTFILE=1 -DUSE_NO_EOF=1 -DUSE_UNITLENGTH_8 -DUSE_EARLYCHANGE_1 -DUSE_LOWBITFIRST_FALSE -DUSE_NO_NULLDEF=1 -DUSE_PIN=1 -DUSE_BINARY=1 l1gbl.pst.tmp.h >l1gbl.pst.tmp.i
<l1gbl.pst.tmp.i >l1gbl.pst.tmp.pin perl -ne's@/\s+(?=\w)@/@g;print if!/^#/&&!/^\s*\Z/'
<l1gbl.pst.tmp.pin >l1gbl.pst.tmp.ps0 ./ps_tiny
<l1gbl.pst.tmp.ps0 >l1gbl.pst.tmp.pst perl -e '$s=$_=join"",<STDIN>; $s=~s@([()\\])@\\$1@g; die if $ARGV[0]!~/^(\w+)/; print "\n% TTT_QUOTE\n/$1 ($s)\n\n"' -- l1gbl.pst
mv -f l1gbl.pst.tmp.pst l1gbl.pst
perl -pe0 bts.ttt l1g8z.pst l1ghz.pst l1gbz.pst l1g8l.pst l1ghl.pst l1gbl.pst >bts1.ttt
./ps_tiny --copy <bts1.ttt >bts2.ttt
perl -x hq.pl <bts2.ttt >bts2.tth
do "hq.pl" failed, '.' is no longer in @INC; did you mean do "./hq.pl"? at hq.pl line 2.
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG2_H -march=native -mtune=native -O2 -pipe -fsigned-char -fno-rtti -fno-exceptions -ansi -pedantic -Wall -W -Wextra -c sam2p_main.cpp
sam2p_main.cpp:152:1: error: expected primary-expression before ‘;’ token
 ;
 ^
make: *** [Makedep:131: sam2p_main.o] Error 1
make: *** Waiting for unfinished jobs....
```

It is suspected a change *like* this may be sufficient to get things working

```diff
-+($0=~/(.*)/s);do$1;die$@if$@;__END__+if 0;
++($0=~/(.*)/s);do"./$1";die$@if$@;__END__+if 0;
```

But I honestly do not understand most of that code, not [even why its necessary](https://en.wikipedia.org/wiki/Cargo_cult)

### Temporary Workaround

People desperate to get this building on 5.26 can set `PERL_USE_UNSAFE_INC=1` in their environment, and `.` will return to `@INC`. However, this is not a long term solution and will be gone around perl 5.30

**Comment by pts** [comment]
Thank you for reporting this in detail!

Fixed in 79a7de171f461a1c79089fa770f0da186e87c723 by changing `perl -x hq.pl` to `perl -x ./hq.pl` in the `Makefile`.
