### ISSUE TITLE
What exactly is 'lzw_codec'?

### ISSUE THREAD

**Issue by lemzwerg** [pts/sam2p#35]
The configure script searches 'lzw_codec'.  However, it is not clear to me which package provides this binary.  Please explain, and please add this info to the README file :-)

**Comment by pts** [comment]
Done in a2d7819107324faf7b0904fc7074f7dd4a0e16c7.

lzw_codec is an external program which can do LZW compression and decompression. If sam2p is configured with `--enable-lzw` (default), then it uses a built-in LZW compressor (and it doesn't use lzw_codec). If sam2p is compiled with `--disable-lzw`, then it uses lzw_codec for LZW compression (and fails if not installed).

If in doubt, then you don't need lzw_codec to do LZW compression with sam2p): just use the built-in LZW compressor by default.

lzw_codec is available from https://github.com/pts/lzw_codec.

**Comment by lemzwerg** [comment]
Thanks for the quick answer and fix!
