### ISSUE TITLE
Crash in XPMTok::readInStr

### ISSUE THREAD

**Issue by SWW13** [pts/sam2p#43]
Dear all,

the following crashes were found by a modified version of the kAFL fuzzer (https://github.com/RUB-SysSec/kAFL).  
I have attached the crashing inputs ([crash_XPMTok--readInStr.zip](https://github.com/pts/sam2p/files/2219977/crash_XPMTok--readInStr.zip)) with backtrace and context during crash.

To reproduce the issue try to convert the crashing input to an `.eps` file:
```bash
$ ./sam2p <crashing input> test.eps
```

Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff70e0801 in __GI_abort () at abort.c:79
#2  0x00007ffff70d039a in __assert_fail_base (fmt=0x7ffff72577d8 "%s%s%s:%u: %s%s"..., assertion=assertion@entry=0x4429c7 "len>=1", file=file@entry=0x442924 "in_xpm.cpp", line=line@entry=179, function=function@entry=0x44299a "void XPMTok::re"...) at assert.c:92
#3  0x00007ffff70d0412 in __GI___assert_fail (assertion=0x4429c7 "len>=1", file=0x442924 "in_xpm.cpp", line=179, function=0x44299a "void XPMTok::re"...) at assert.c:101
#4  0x0000000000414238 in XPMTok::readInStr(char*, unsigned int) ()
#5  0x0000000000413e6f in in_xpm_reader(Image::Loader::UFD*, SimBuffer::Flat const&) ()
#6  0x00000000004319a6 in Image::load(Image::Loader::UFD*, SimBuffer::Flat const&, char const*) ()
#7  0x0000000000401e59 in run_sam2p_engine(Files::FILEW&, Files::FILEW&, char const* const*, bool) ()
#8  0x0000000000406134 in main ()
#9  0x00007ffff70c1b97 in __libc_start_main (main=0x405f90 <main>, argc=3, argv=0x7fffffffe538, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe528) at ../csu/libc-start.c:310
#10 0x000000000040157a in _start ()
```

Tested against the [binaries.zip](https://github.com/pts/sam2p/files/2219995/binaries.zip) compiled with: clang asan, clang and g++.

We can verify the issue against commit 5ed411dd145e77994538d261191d6be1b3dd9c38.

Credits: Simon Wörner, Sergej Schumilo, Cornelius Aschermann (all of Ruhr-Universität Bochum)

**Comment by pts** [comment]
Thank you for reporting this! Fixed in 53f6c89c24ecb53e34d0aaa085f40800c677aea2.
