### ISSUE TITLE
out of memory and abort

### ISSUE THREAD

**Issue by cxht** [pts/sam2p#64]
HI!
When I use sam2p 0.49.4 as `./sam2p ../sam2p/crash/43.bmp EPS: /dev/null`, it shows "out of memory"
`This is sam2p 0.49.4.
Available Loaders: PS PDF JAI PNG JPEG TIFF PNM BMP LBM XPM PCX TGA.
Available Appliers: XWD Meta Empty BMP PNG TIFF6 TIFF6-JAI JPEG-JAI JPEG PNM XPM PSL1C PSL23+PDF PSL2+PDF-JAI P-TrOpBb.
out of memory
Aborted (core dumped)
`
and here is the input file.
![43](https://user-images.githubusercontent.com/7196400/60494184-e039c300-9ce0-11e9-956a-8afd13b64db1.jpg)

**Comment by pts** [comment]
Thank you for reporting this! It's fixed in 93d5cedf4a5aaf769ba5f749d968f3ffb244c366. The new behavior is a friendlier error message:

```
sam2p: Error: PNM: invalid xres while loading
```
