### ISSUE TITLE
Separate code and docs?

### ISSUE THREAD

**Issue by zvezdochiot** [pts/sam2p#70]
Maybe move code (`*.c` `*.cc` `*.ci` `*.cpp` `*.h` `*.hpp`) to `./src` (new path)?

**Comment by pts** [comment]
Thank you for suggesting this refactoring. The sam2p development team (currently 1 person) doesn't have free capacity for such refactorings, so this is unlikely to happen until sam2p receives funding.

Also I fail to see the specific, immediate benefits of moving files around. Also I fail to see the specific problem the move would solve.

**Comment by zvezdochiot** [comment]
No time. Ok.
