### ISSUE TITLE
Windows 0.49.4 release needs static link to libgcc

### ISSUE THREAD

**Issue by Adreitz** [pts/sam2p#78]
Hello.

I was using sam2p as a part of pdfsizeopt in Windows 10 and tried to download the newest version from here. It looks like it was not properly compiled. Running it from CLI produces a pop-up saying "The code execution cannot proceed because libgcc_s_sjlj-1.dll was not found. Reinstalling the program may fix this problem." According to this comment, https://www.qtcentre.org/threads/39639-MinGW-w64-dependency-on-LIBGCC_S_SJLJ-1-DLL, a linker flag needs to be added during compilation to remove the library dependency. As it is now, the .exe is not truly portable.

Thanks,

Aaron Reitz

**Comment by zvezdochiot** [comment]
Hi @Adreitz .

See https://github.com/ImageProcessing-ElectronicPublications/sam2p/releases/tag/v0.49.4

**Comment by pts** [comment]
This flag needs to be added: `-static-libgcc`.

**Comment by cdokolas** [comment]
I can confirm that 0.49.4 does not work on Windows 11, while 0.49.3 works fine.

**Comment by pts** [comment]
Thank you for reporting this!

Recompiled with `-static-libgcc`, updated https://github.com/pts/sam2p/releases/download/v0.49.4/sam2p.exe
